= DevConf.cz 2015

:hp-tags: Codearte, DevConf, DevConf.cz, Conference, OSS, Kubernetes, Docker, OpenShift

_coauthored by Marcin Zajączkowski (https://solidsoft.wordpress.com)_

In February, a few of Codearte team members visited the DevConf.cz 2015 conference. Not surprisingly for an event organised by RedHat, infrastructure-related topics were among the main points of interest. One of the topics most spoken about was definitely the Docker project. Issues related to both securing the Docker containers and creating super-privileged containers were covered in two interesting presentations by Dan Walsh. Apart from this, Kubernetes - a new cloud-based orchestration tool for Docker containers that allows for scheduling activities and managing workload- was spoken about a lot and a workshop on its practical use was held by Michael P. McGrath. 

The revolutionary Kubernetes project has also strongly affected OpenShift and the resulting change of approach was discussed during the presentation done by Michal Fojtik, Jakub Hadvig and Marek Jelen. The central idea behind OpenShift v3, which differs significantly from the earlier versions, is to have user applications running in Docker containers that will be orchestrated and managed by Kubernetes. To easily manage the entire solution you can use the integration platform that is Fabric8. Its practical demonstration was prepared and presented by Marek Schmidt.

Not only DevOps could be happy at DevConf.cz. In addition to all the container and Docker related talks there were a number of programming presentations. Ladislav Thon had an interesting talk about writing custom annotation processors, Xavier Coulon presented an innovative way of recovering original lambda expression form from the bytecode to create queries to MongoDB. Besides that, it was possible to get to know about new features in old/ new Python 3, get started with Go and Ceylon or learn about property-based testing in Haskell.

In addition to regular talks at the end of the first two days there were 1,5 h long slots reserved for 10 minute length lightning talks. The proposals were put on the whiteboard during a day and attendees could vote for interesting topics. This year there were over 40 talks on various topics including automated testing, changes in upcoming RPM version, firewall configuration, using Python on Android and simplification of testing code with Java 8. It was a great way to get a quick introduction into multiple topics.

Apart from this, there were also a few presentations dedicated to databases, such as the presentation that addressed issues related to the lack of transactions in NoSQL databases and the various solutions that could be adopted in order to benefit from some of the transaction-specific features in the NoSQL world delivered by Mark Little. Additionally, there was also an entire track related to testing, featuring such topics as test automation tools, testing frameworks, as well as mobile and performance tests.                                        

As the presentations were being recorded, those of you who could not go to Brno this year can still watch them on the RedHat youtube channel - you might find many of them interesting and inspiring. We most certainly did and we are planning on attending DevConf.cz again next year.